name: CI

on:
  push:

jobs:
  build-and-test:
    name: build and test
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26

      - run: nix build --print-build-logs
